services:
  frontend:
    build: .
    ports:
      - "8001:8000"
    environment:
      - DEBUG=True
      - FASTAPI_BASE_URL=http://fastapi:8000
    volumes:
      - .:/app
    networks:
      - estetica_network

networks:
  estetica_network:
    driver: bridge
